import type { Metadata } from "next";
import tracesData from "../../public/traces.json";
import { answersMatch, cleanAnswer, extractReasoning } from "../../lib/parse";

export const metadata: Metadata = {
  title: "Traces — real reasoning, side by side",
  description:
    "Full base-vs-tuned reasoning traces on held-out GSM8K problems, including the case where both models fail.",
};

type Trace = {
  id: string;
  source: string;
  split: string;
  question: string;
  gold: string;
  models: { base: { raw: string; answer: string | null }; tuned: { raw: string; answer: string | null } };
};

const TRACES = (tracesData as { traces: Trace[] }).traces;

function Verdict({ label, answer, gold }: { label: string; answer: string | null; gold: string }) {
  const ok = answersMatch(answer, gold);
  const clean = cleanAnswer(answer);
  return (
    <span className={`vchip ${ok ? "ok" : "bad"}`}>
      {label} · {clean ?? "no parseable answer"} {ok ? "✓" : "✗"}
    </span>
  );
}

function Pane({ kind, raw }: { kind: "base" | "tuned"; raw: string }) {
  const tagged = raw.includes("<answer>");
  return (
    <div className={`col ${kind}`}>
      <h3>
        {kind === "tuned" ? "GRPO-tuned" : "Base"}{" "}
        <span className={`badge ${kind}`}>
          {kind === "tuned" ? "Qwen2.5-1.5B + GRPO" : "Qwen2.5-1.5B-Instruct"}
        </span>
      </h3>
      <div className="sub sub-row">
        <span>reasoning trace</span>
        {!tagged && <span className="livetag error">no answer block</span>}
      </div>
      <div className="reasoning trace-pane">{extractReasoning(raw)}</div>
    </div>
  );
}

export default function Traces() {
  return (
    <div className="wrap">
      <section className="pg-head">
        <div className="sec-label">Traces · receipts</div>
        <h2>What actually changed in the reasoning</h2>
        <p className="pg-lede">
          Aggregate percentages tell you something improved. They don&apos;t tell you what. These are
          complete, unedited outputs from both models on the same held-out problems — the arithmetic
          the base model drops, and the step the tuned model doesn&apos;t.
        </p>
      </section>

      <section>
        <div className="callout">
          <div className="callout-k">Read these for what they are</div>
          <p>
            The first five were <b>selected</b> because the two models disagree — that&apos;s what
            makes them worth reading, and it also means they are not a random sample. The tuned model
            scores <b>70.0%</b>, not 100%, and the last card is a problem where{" "}
            <b>both models fail</b>. It&apos;s here on purpose: a gallery of nothing but wins is a
            highlight reel, not evidence.
          </p>
        </div>
      </section>

      {TRACES.map((t, i) => (
        <section key={t.id} className="trace">
          <div className="trace-head">
            <span className="trace-num">{String(i + 1).padStart(2, "0")}</span>
            <span className="trace-split">{t.split}</span>
          </div>
          <p className="trace-q">{t.question}</p>

          <div className="trace-verdicts">
            <Verdict label="Base" answer={t.models.base.answer} gold={t.gold} />
            <Verdict label="GRPO-tuned" answer={t.models.tuned.answer} gold={t.gold} />
            <span className="gold">gold answer: {t.gold}</span>
          </div>

          <details className="trace-details">
            <summary>Read both reasoning traces</summary>
            <div className="grid">
              <Pane kind="base" raw={t.models.base.raw} />
              <Pane kind="tuned" raw={t.models.tuned.raw} />
            </div>
          </details>
        </section>
      ))}

      <section>
        <div className="prose">
          <p>
            Generated by <code>demo/gen_traces.py</code> from{" "}
            <code>docs/sample_traces.md</code> and <code>demo/public/examples.json</code>, both
            committed. Nothing here is edited for readability — the LaTeX fragments and the
            repetition are what the models actually emitted.
          </p>
        </div>
      </section>
    </div>
  );
}
